/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.Color;
import Client.Client;
import util.Constants;

/**
 *
 * @author YuanZhan
 */
public class GUIForHotelBB extends javax.swing.JFrame {

    private Client client;
    private String[] cbOfCity = {"No City", "No City", "No City"};
    private String[] cbOfHotel = {"No Hotel", "No Hotel", "No Hotel"};

    /**
     * Creates new form GUIForHotelBB
     */
    public GUIForHotelBB() {
        initComponents();
        client = new Client();
        this.secondStagePanel.setVisible(false);
        this.thirdStagePanel.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        feedbackDialog = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        feedbackLable = new javax.swing.JLabel();
        closeDialogBtn = new javax.swing.JButton();
        loginBtn = new javax.swing.JButton();
        firstStagePanel = new javax.swing.JPanel();
        cityListComboBox = new javax.swing.JComboBox<>();
        chooseCity = new javax.swing.JButton();
        hotelListComboBox = new javax.swing.JComboBox<>();
        chooseHotel = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        secondStagePanel = new javax.swing.JPanel();
        inYearComboBox = new javax.swing.JComboBox<>();
        inMonthComboBox = new javax.swing.JComboBox<>();
        outYearComboBox = new javax.swing.JComboBox<>();
        outMonthComboBox = new javax.swing.JComboBox<>();
        Year = new javax.swing.JLabel();
        Year1 = new javax.swing.JLabel();
        Year2 = new javax.swing.JLabel();
        Year3 = new javax.swing.JLabel();
        Year4 = new javax.swing.JLabel();
        Year5 = new javax.swing.JLabel();
        inDateComboBox = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        outDateComboBox = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        roomListComboBox = new javax.swing.JComboBox<>();
        checkRoomAvailBtn = new javax.swing.JButton();
        roomIsAvailLabel = new javax.swing.JLabel();
        Year6 = new javax.swing.JLabel();
        roomRate = new javax.swing.JLabel();
        thirdStagePanel = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        bkingIDTxtField = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        custIDTxtField = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        fnameTxtField = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        lnameTxtField = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        emailAddrTxtField = new javax.swing.JTextField();
        ccnTxtField = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        errorLabel = new javax.swing.JLabel();

        feedbackDialog.setSize(new java.awt.Dimension(400, 400));

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));

        feedbackLable.setText("       ");

        closeDialogBtn.setText("Close");
        closeDialogBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeDialogBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addComponent(feedbackLable))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addComponent(closeDialogBtn)))
                .addContainerGap(163, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addComponent(feedbackLable)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 132, Short.MAX_VALUE)
                .addComponent(closeDialogBtn)
                .addGap(73, 73, 73))
        );

        javax.swing.GroupLayout feedbackDialogLayout = new javax.swing.GroupLayout(feedbackDialog.getContentPane());
        feedbackDialog.getContentPane().setLayout(feedbackDialogLayout);
        feedbackDialogLayout.setHorizontalGroup(
            feedbackDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        feedbackDialogLayout.setVerticalGroup(
            feedbackDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 204, 255));

        loginBtn.setBackground(new java.awt.Color(204, 204, 204));
        loginBtn.setText("Log in");
        loginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginBtnActionPerformed(evt);
            }
        });

        firstStagePanel.setBackground(new java.awt.Color(0, 204, 204));

        cityListComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(cbOfCity));
        cityListComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cityListComboBoxActionPerformed(evt);
            }
        });

        chooseCity.setText("Choose");
        chooseCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chooseCityActionPerformed(evt);
            }
        });

        hotelListComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(cbOfHotel));

        chooseHotel.setText("Choose");
        chooseHotel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chooseHotelActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Oriya MN", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 102, 102));
        jLabel1.setText("Hotel");

        jLabel4.setFont(new java.awt.Font("Oriya MN", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 102, 102));
        jLabel4.setText("City");

        javax.swing.GroupLayout firstStagePanelLayout = new javax.swing.GroupLayout(firstStagePanel);
        firstStagePanel.setLayout(firstStagePanelLayout);
        firstStagePanelLayout.setHorizontalGroup(
            firstStagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(firstStagePanelLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(firstStagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chooseCity, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cityListComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(firstStagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(hotelListComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(chooseHotel))
                .addGap(81, 81, 81))
        );
        firstStagePanelLayout.setVerticalGroup(
            firstStagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(firstStagePanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(firstStagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(firstStagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cityListComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hotelListComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(firstStagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chooseCity)
                    .addComponent(chooseHotel))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        secondStagePanel.setBackground(new java.awt.Color(102, 153, 255));

        inYearComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2017", "2018", "2019", "2020" }));

        inMonthComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" }));

        outYearComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2017", "2018", "2019", "2020" }));

        outMonthComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" }));

        Year.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        Year.setForeground(new java.awt.Color(255, 255, 255));
        Year.setText("Year");

        Year1.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        Year1.setForeground(new java.awt.Color(255, 255, 255));
        Year1.setText("Year");

        Year2.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        Year2.setForeground(new java.awt.Color(255, 255, 255));
        Year2.setText("Month");

        Year3.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        Year3.setForeground(new java.awt.Color(255, 255, 255));
        Year3.setText("Month");

        Year4.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        Year4.setForeground(new java.awt.Color(255, 255, 255));
        Year4.setText("Day");

        Year5.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        Year5.setForeground(new java.awt.Color(255, 255, 255));
        Year5.setText("Day");

        inDateComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1"}));
        inDateComboBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                inDateComboBoxMouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Oriya MN", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 102, 102));
        jLabel2.setText("Check Out Date");

        outDateComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1"}));
        outDateComboBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                outDateComboBoxMouseClicked(evt);
            }
        });
        outDateComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                outDateComboBoxActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Oriya MN", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 102, 102));
        jLabel3.setText("Check In Date");

        jLabel5.setFont(new java.awt.Font("Oriya MN", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 102, 102));
        jLabel5.setText("Room");

        roomListComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "No Room" }));

        checkRoomAvailBtn.setBackground(new java.awt.Color(204, 204, 204));
        checkRoomAvailBtn.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        checkRoomAvailBtn.setForeground(new java.awt.Color(204, 0, 0));
        checkRoomAvailBtn.setText("Check");
        checkRoomAvailBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkRoomAvailBtnActionPerformed(evt);
            }
        });

        roomIsAvailLabel.setText("     ");

        Year6.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        Year6.setForeground(new java.awt.Color(255, 255, 255));
        Year6.setText("Rate:");

        roomRate.setForeground(new java.awt.Color(255, 51, 51));
        roomRate.setText("$0.0");

        javax.swing.GroupLayout secondStagePanelLayout = new javax.swing.GroupLayout(secondStagePanel);
        secondStagePanel.setLayout(secondStagePanelLayout);
        secondStagePanelLayout.setHorizontalGroup(
            secondStagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(secondStagePanelLayout.createSequentialGroup()
                .addGroup(secondStagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(secondStagePanelLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(secondStagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addGroup(secondStagePanelLayout.createSequentialGroup()
                                .addComponent(Year)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(inYearComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Year2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(inMonthComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Year4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(inDateComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(secondStagePanelLayout.createSequentialGroup()
                                .addGroup(secondStagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(secondStagePanelLayout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(21, 21, 21)
                                        .addComponent(roomListComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(14, 14, 14)
                                        .addComponent(Year6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(roomRate))
                                    .addGroup(secondStagePanelLayout.createSequentialGroup()
                                        .addComponent(Year1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(outYearComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(Year3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(outMonthComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(Year5)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(secondStagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(checkRoomAvailBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(outDateComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(secondStagePanelLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(roomIsAvailLabel)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        secondStagePanelLayout.setVerticalGroup(
            secondStagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(secondStagePanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(secondStagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Year)
                    .addComponent(inYearComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Year2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inMonthComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Year4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inDateComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(secondStagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Year1)
                    .addComponent(outYearComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Year3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(outMonthComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Year5, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(outDateComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(secondStagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(roomListComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkRoomAvailBtn)
                    .addComponent(Year6, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(roomRate))
                .addGap(18, 18, 18)
                .addComponent(roomIsAvailLabel)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        thirdStagePanel.setBackground(new java.awt.Color(255, 204, 153));

        jLabel6.setFont(new java.awt.Font("Oriya MN", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Booking");

        jLabel7.setFont(new java.awt.Font("Oriya MN", 1, 12)); // NOI18N
        jLabel7.setText("Booking ID");

        jLabel10.setFont(new java.awt.Font("Oriya MN", 1, 12)); // NOI18N
        jLabel10.setText("Customer ID");

        jLabel11.setFont(new java.awt.Font("Oriya MN", 1, 12)); // NOI18N
        jLabel11.setText("First Name");

        jLabel12.setFont(new java.awt.Font("Oriya MN", 1, 12)); // NOI18N
        jLabel12.setText("Last Name");

        jLabel13.setFont(new java.awt.Font("Oriya MN", 1, 12)); // NOI18N
        jLabel13.setText("Email Addr");

        jLabel14.setFont(new java.awt.Font("Oriya MN", 1, 12)); // NOI18N
        jLabel14.setText("Credit Card Number");

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Book");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        errorLabel.setForeground(new java.awt.Color(255, 0, 0));
        errorLabel.setText("      ");

        javax.swing.GroupLayout thirdStagePanelLayout = new javax.swing.GroupLayout(thirdStagePanel);
        thirdStagePanel.setLayout(thirdStagePanelLayout);
        thirdStagePanelLayout.setHorizontalGroup(
            thirdStagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(thirdStagePanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(thirdStagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(thirdStagePanelLayout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(18, 18, 18)
                        .addComponent(ccnTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(thirdStagePanelLayout.createSequentialGroup()
                        .addGroup(thirdStagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(thirdStagePanelLayout.createSequentialGroup()
                                .addComponent(errorLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton1))
                            .addGroup(thirdStagePanelLayout.createSequentialGroup()
                                .addGroup(thirdStagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(thirdStagePanelLayout.createSequentialGroup()
                                        .addComponent(jLabel13)
                                        .addGap(18, 18, 18)
                                        .addComponent(emailAddrTxtField))
                                    .addGroup(thirdStagePanelLayout.createSequentialGroup()
                                        .addComponent(jLabel11)
                                        .addGap(18, 18, 18)
                                        .addComponent(fnameTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel12)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lnameTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(49, 49, 49))))
            .addGroup(thirdStagePanelLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(thirdStagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addGroup(thirdStagePanelLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(bkingIDTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel10)
                        .addGap(18, 18, 18)
                        .addComponent(custIDTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        thirdStagePanelLayout.setVerticalGroup(
            thirdStagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(thirdStagePanelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(thirdStagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(bkingIDTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(custIDTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(thirdStagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(fnameTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(lnameTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(thirdStagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(emailAddrTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(thirdStagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(ccnTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(thirdStagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(errorLabel))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(firstStagePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(secondStagePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(thirdStagePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(loginBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(loginBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(firstStagePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(secondStagePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(thirdStagePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cityListComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cityListComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cityListComboBoxActionPerformed

    private void loginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBtnActionPerformed
        // TODO add your handling code here:
        cbOfCity = this.client.getAllCitiesArray();
        cityListComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(cbOfCity));
    }//GEN-LAST:event_loginBtnActionPerformed

    private void chooseCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chooseCityActionPerformed
        // TODO add your handling code here:
//        getHotelsListInCity
        String cityName = (String) this.cityListComboBox.getSelectedItem();
        cbOfHotel = this.client.getHotelsListInCity(cityName);
        hotelListComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(cbOfHotel));
    }//GEN-LAST:event_chooseCityActionPerformed

    private void inDateComboBoxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inDateComboBoxMouseClicked
        // TODO add your handling code here:
        String inMonth = (String) this.inMonthComboBox.getSelectedItem();
        if (inMonth.equals("January") || inMonth.equals("March")
                || inMonth.equals("May") || inMonth.equals("July")
                || inMonth.equals("August") || inMonth.equals("October")
                || inMonth.equals("December")) {

            String[] dayDTM = new String[31];
            for (int i = 1; i <= 31; i++) {
                dayDTM[i - 1] = i + "";
            }
            this.inDateComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(dayDTM));
        } else if (inMonth.equals("April") || inMonth.equals("June")
                || inMonth.equals("September") || inMonth.equals("November")) {
            String[] dayDTM = new String[30];
            for (int i = 1; i <= 30; i++) {
                dayDTM[i - 1] = i + "";
            }
            this.inDateComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(dayDTM));
        } else {
            String inYear = (String) this.inYearComboBox.getSelectedItem();
            int year = Integer.parseInt(inYear);
            if (year % 4 == 0) {
                String[] dayDTM = new String[29];
                for (int i = 1; i <= 29; i++) {
                    dayDTM[i - 1] = i + "";
                }
                this.inDateComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(dayDTM));
            } else {
                String[] dayDTM = new String[28];
                for (int i = 1; i <= 28; i++) {
                    dayDTM[i - 1] = i + "";
                }
                this.inDateComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(dayDTM));
            }
        }
    }//GEN-LAST:event_inDateComboBoxMouseClicked

    private void outDateComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_outDateComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_outDateComboBoxActionPerformed

    private void outDateComboBoxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_outDateComboBoxMouseClicked
        // TODO add your handling code here:
        String outMonth = (String) this.outMonthComboBox.getSelectedItem();
        if (outMonth.equals("January") || outMonth.equals("March")
                || outMonth.equals("May") || outMonth.equals("July")
                || outMonth.equals("August") || outMonth.equals("October")
                || outMonth.equals("December")) {

            String[] dayDTM = new String[31];
            for (int i = 1; i <= 31; i++) {
                dayDTM[i - 1] = i + "";
            }
            this.outDateComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(dayDTM));
        } else if (outMonth.equals("April") || outMonth.equals("June")
                || outMonth.equals("September") || outMonth.equals("November")) {
            String[] dayDTM = new String[30];
            for (int i = 1; i <= 30; i++) {
                dayDTM[i - 1] = i + "";
            }
            this.outDateComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(dayDTM));
        } else {
            String outYear = (String) this.outYearComboBox.getSelectedItem();
            int year = Integer.parseInt(outYear);
            if (year % 4 == 0) {
                String[] dayDTM = new String[29];
                for (int i = 1; i <= 29; i++) {
                    dayDTM[i - 1] = i + "";
                }
                this.outDateComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(dayDTM));
            } else {
                String[] dayDTM = new String[28];
                for (int i = 1; i <= 28; i++) {
                    dayDTM[i - 1] = i + "";
                }
                this.outDateComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(dayDTM));
            }
        }
    }//GEN-LAST:event_outDateComboBoxMouseClicked

    private void chooseHotelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chooseHotelActionPerformed
        String hotel = (String) this.hotelListComboBox.getSelectedItem();
        String city = (String) this.cityListComboBox.getSelectedItem();
        String msg = hotel + "_" + city;
        String[] roomDTM = new String[Constants.MAX_ROOM_NUM];
//        cbOfCity = this.client.getAllCitiesArray();
//        cityListComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(cbOfCity));
        roomDTM = this.client.getRooms(msg);
        roomListComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(roomDTM));
        this.secondStagePanel.setVisible(true);
    }//GEN-LAST:event_chooseHotelActionPerformed

    private void checkRoomAvailBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkRoomAvailBtnActionPerformed
        // TODO add your handling code here:
        this.getRoomRate();

        // initial
        this.roomIsAvailLabel.setText("   ");

        String city = (String) this.cityListComboBox.getSelectedItem();
        String hotel = (String) this.hotelListComboBox.getSelectedItem();
        String inYear = (String) this.inYearComboBox.getSelectedItem();
        String inMonth = (String) this.inMonthComboBox.getSelectedItem();
        String inDay = (String) this.inDateComboBox.getSelectedItem();
        String outYear = (String) this.outYearComboBox.getSelectedItem();
        String outMonth = (String) this.outMonthComboBox.getSelectedItem();
        String outDay = (String) this.outDateComboBox.getSelectedItem();
        String roomID = (String) this.roomListComboBox.getSelectedItem();

        // syntax
        int inMonthNum = Constants.convertMMtoNum(inMonth);
        int outMonthNum = Constants.convertMMtoNum(outMonth);
        // avoid in date > out date --> really simple way
        int in = Integer.parseInt(inYear) * 1000 + inMonthNum * 100 + Integer.parseInt(inDay);
        int out = Integer.parseInt(outYear) * 1000 + outMonthNum * 100 + Integer.parseInt(outDay);
        if (in >= out) {
            this.roomIsAvailLabel.setForeground(Color.red);
            this.roomIsAvailLabel.setText("Check in date should be later than out date!");
        } else {
            // indate syntax
            String inDate = inYear + "-" + inMonthNum + "-" + inDay + " 00:00:00";
            String outDate = outYear + "-" + outMonthNum + "-" + outDay + " 00:00:00";
            String checkStr = city + "_" + hotel + "_" + inDate + "_" + outDate + "_" + roomID;
            System.out.println(checkStr);

            // invoke method
            if (this.client.checkIfRoomAvailable(checkStr)) {
                this.roomIsAvailLabel.setForeground(Color.GREEN);
                this.roomIsAvailLabel.setText("Room is Available!");
                this.thirdStagePanel.setVisible(true);

            } else {
                this.roomIsAvailLabel.setForeground(Color.red);
                this.roomIsAvailLabel.setText("Room is NOT Available!");
            }
        }

    }//GEN-LAST:event_checkRoomAvailBtnActionPerformed

    private void getRoomRate(){
        String hotelName = (String) this.hotelListComboBox.getSelectedItem();
        String roomID = (String) this.roomListComboBox.getSelectedItem();
        String roomMsg = hotelName + "_" + roomID;
        this.roomRate.setText( this.client.getRoomRate(roomMsg));
        
    }
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        // initialization
        this.errorLabel.setText("      ");

        String bkingID = this.bkingIDTxtField.getText();
        String custID = this.custIDTxtField.getText();
        String fname = this.fnameTxtField.getText();
        String lname = this.lnameTxtField.getText();
        String email = this.emailAddrTxtField.getText();
        String ccn = this.ccnTxtField.getText();
        String city = (String) this.cityListComboBox.getSelectedItem();
        String hotel = (String) this.hotelListComboBox.getSelectedItem();

        String inYear = (String) this.inYearComboBox.getSelectedItem();
        String inMonth = (String) this.inMonthComboBox.getSelectedItem();
        String inDay = (String) this.inDateComboBox.getSelectedItem();
        String outYear = (String) this.outYearComboBox.getSelectedItem();
        String outMonth = (String) this.outMonthComboBox.getSelectedItem();
        String outDay = (String) this.outDateComboBox.getSelectedItem();
        String roomID = (String) this.roomListComboBox.getSelectedItem();
        int inMonthNum = Constants.convertMMtoNum(inMonth);
        int outMonthNum = Constants.convertMMtoNum(outMonth);
        String inDate = inYear + "-" + inMonthNum + "-" + inDay + " 00:00:00";
        String outDate = outYear + "-" + outMonthNum + "-" + outDay + " 00:00:00";
        //hilton_cust1_Yuan_Zhan_yzh@g.com_1234567890123456_rh001_2017-3-3 00:00:00_2017-3-4 00:00:00_1

        //validation
        if (bkingID.trim().isEmpty()) {
            this.errorLabel.setText("Booking ID can't be empty");
        } else if (custID.trim().isEmpty()) {
            this.errorLabel.setText("Customer ID can't be empty");
        } else if (fname.trim().isEmpty()) {
            this.errorLabel.setText("First name can't be empty");
        } else if (lname.trim().isEmpty()) {
            this.errorLabel.setText("Last name can't be empty");
        } else if (email.trim().isEmpty()) {
            this.errorLabel.setText("Email can't be empty");
        } else if (ccn.trim().isEmpty()) {
            this.errorLabel.setText("Credit card number can't be empty");
        } else {
            // REGEX
            if (!Constants.checkIfisEmailAddr(email.trim())) {
                this.errorLabel.setText("Wrong Email Syntax");
            } else if (!Constants.checkIfisCreditCardNumber(ccn.trim())) {
                this.errorLabel.setText("Wrong Credit Card Number Systex");
            } else {
                String bkingStr = hotel + "_" + custID + "_" + fname + "_" + lname + "_" + email + "_" + ccn + "_" + roomID + "_" + inDate + "_" + outDate + "_" + bkingID;

                String checkStr = city + "_" + hotel + "_" + inDate + "_" + outDate + "_" + roomID;
                System.out.println("!!!!!!!!!!!!!!!!" + checkStr);
                if (this.client.checkIfRoomAvailable(checkStr)) {

                    if (this.client.makeABookingWithFeedback(bkingStr)) {
                        this.feedbackLable.setText("Booking Successfully");
                        this.feedbackDialog.setVisible(true);
                    } else {
                        this.feedbackLable.setText("Errors occur during booking");
                        this.feedbackDialog.setVisible(true);
                    }
                } else {
                    this.feedbackLable.setText("Sorry, room has just been booked");
                    this.feedbackDialog.setVisible(true);
                }
            }
        }


    }//GEN-LAST:event_jButton1ActionPerformed

    private void closeDialogBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeDialogBtnActionPerformed
        // TODO add your handling code here:
        this.thirdStagePanel.setVisible(false);
        this.feedbackLable.setText("No FeedBack");
        this.feedbackDialog.setVisible(false);
    }//GEN-LAST:event_closeDialogBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIForHotelBB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIForHotelBB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIForHotelBB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIForHotelBB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIForHotelBB().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Year;
    private javax.swing.JLabel Year1;
    private javax.swing.JLabel Year2;
    private javax.swing.JLabel Year3;
    private javax.swing.JLabel Year4;
    private javax.swing.JLabel Year5;
    private javax.swing.JLabel Year6;
    private javax.swing.JTextField bkingIDTxtField;
    private javax.swing.JTextField ccnTxtField;
    private javax.swing.JButton checkRoomAvailBtn;
    private javax.swing.JButton chooseCity;
    private javax.swing.JButton chooseHotel;
    private javax.swing.JComboBox<String> cityListComboBox;
    private javax.swing.JButton closeDialogBtn;
    private javax.swing.JTextField custIDTxtField;
    private javax.swing.JTextField emailAddrTxtField;
    private javax.swing.JLabel errorLabel;
    private javax.swing.JDialog feedbackDialog;
    private javax.swing.JLabel feedbackLable;
    private javax.swing.JPanel firstStagePanel;
    private javax.swing.JTextField fnameTxtField;
    private javax.swing.JComboBox<String> hotelListComboBox;
    private javax.swing.JComboBox<String> inDateComboBox;
    private javax.swing.JComboBox<String> inMonthComboBox;
    private javax.swing.JComboBox<String> inYearComboBox;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField lnameTxtField;
    private javax.swing.JButton loginBtn;
    private javax.swing.JComboBox<String> outDateComboBox;
    private javax.swing.JComboBox<String> outMonthComboBox;
    private javax.swing.JComboBox<String> outYearComboBox;
    private javax.swing.JLabel roomIsAvailLabel;
    private javax.swing.JComboBox<String> roomListComboBox;
    private javax.swing.JLabel roomRate;
    private javax.swing.JPanel secondStagePanel;
    private javax.swing.JPanel thirdStagePanel;
    // End of variables declaration//GEN-END:variables
}
